### ISSUE TITLE
Can't interact with the website when using firefox

### ISSUE THREAD

**Issue by bibufr** [Axwabo/914#1]
Small oversight, you might have forgotten to remove the loading screen element on Firefox, indirectly resulting in not being able to interact with anything. Tested with chrome and edge and both work as intended, only Firefox seems to have this issue (even private browser has the issue).
Vid: https://www.youtube.com/watch?v=vRcQrT0rxoY
I used uBlock to remove the top layer of the website on Firefox, on chrome and edge that element isn't there for some reason.

**Comment by Axwabo** [comment]
Thanks for reporting! It seems that the animation won't set the display property to none after completing.
I'll be implementing a quick fix now.
